job:
  name: "train-event-consumer"
  environment:
    properties:
      pipeline.operator-chaining.enabled: "false"

kafka-source:
  bootstrap-servers:
    - "kafka:29092"
  group-id: "events-consumer-v1"
  topics:
    - "chained-events"
  starting-offsets: "EARLIEST"
kafka-sink:
  bootstrap-servers:
    - "kafka:29092"
  topic: "delayed-events"