job:
  name: "train-event-consumer"
  environment:
    properties:
      pipeline.operator-chaining.enabled: "false"

kafka:
  bootstrap-servers:
    - "kafka:29092"
  group-id: "events-consumer-v1"
  topics:
    - "chained-events"
  starting-offsets: "EARLIEST"