train:
  producer:
    duration: "PT5S"
  regular-delay-in-ms: 1000
  chance-of-huge-delay: 10
  huge-delay-in-ms: 10000
  stations:
    - "Noisy-Champs"
    - "Acton Central"
    - "Canary Wharf"
    - "Vincennes"
    - "Châtelet les Halles"
    - "La défense"
    - "Leicester Square"
    - "Picadilly Circus"